/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jnidemo_MainActivity */

#ifndef _Included_com_jnidemo_MainActivity
#define _Included_com_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jnidemo_MainActivity
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jnidemo_MainActivity_stringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
